language: python

python:
 - "3.6"

script:
  - .travis/check-manifest.sh
  - flake8
  - black . --check -t py36
  - yamllint system_baseline/openapi/mgmt_api.spec.yaml
  - yamllint system_baseline/openapi/api.spec.yaml

install:
  - pip install pipenv
  - pipenv install --dev
  - pip install codecov
