---
openapi: 3.0.1
info:
  version: "1.0"
  title: System Baseline Backend Service
  description: Service that returns system baselines
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: "{{ path_prefix }}{{ app_name }}/v0"

paths:
  /baselines:
    get:
      summary: fetch list of Baseline IDs
      description: "Fetch the list of Baseline IDs"
      operationId: system_baseline.views.v0.get_baselines
      parameters:
        - $ref: '#/components/parameters/offsetParam'
        - $ref: '#/components/parameters/limitParam'
      responses:
        '200':
          description: a paginated list of baselines
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataPage'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: create a baseline
      description: "create a baseline"
      operationId: system_baseline.views.v0.create_baseline
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BaselineIn"
              x-body-name: system_baseline_in
      responses:
        '200':
          description: a created baseline object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Baseline"
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /baselines/{baseline_ids}:
    parameters:
      - $ref: '#/components/parameters/BaselineIds'
    get:
      summary: fetch one or more Baseline objects
      description: "Fetch one Baseline object"
      operationId: system_baseline.views.v0.get_baselines_by_ids
      parameters:
        - $ref: '#/components/parameters/offsetParam'
        - $ref: '#/components/parameters/limitParam'
      responses:
        '200':
          description: a paginated list of baselines
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataPage'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      summary: delete one or more baselines
      description: "delete one or more baselines"
      operationId: system_baseline.views.v0.delete_baselines_by_ids
      responses:
        '200':
          description: a success message
          content:
            application/json:
              schema:
                type: string
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /baselines/{baseline_id}:
    parameters:
      - $ref: '#/components/parameters/BaselineId'
    patch:
      summary: update a baseline
      description: "update a baseline"
      operationId: system_baseline.views.v0.update_baseline
      requestBody:
        required: true
        content:
          application/json:
            schema:
              x-body-name: system_baseline_patch
              type: object
              required:
                - display_name
                - facts_patch
              properties:
                display_name:
                  type: string
                facts_patch:
                  type: array
                  items:
                    $ref: "#/components/schemas/JsonPatch"
      responses:
        '200':
          description: a list of updated Baseline objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Baseline"
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: copy a baseline
      description: "copy a baseline, returning a new ID"
      operationId: system_baseline.views.v0.copy_baseline_by_id
      parameters:
        - in: query
          name: display_name
          required: true
          schema:
            type: string
          description: display name of copied baseline
      responses:
        '200':
          description: a created baseline object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Baseline"
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  responses:
    InternalServerError:
      description: "An internal server error has occurred."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    BadRequest:
      description: "The server could could not process the current request."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
  securitySchemes:
    ApiKeyAuth:
      description: "Identity header provided by 3scale"
      in: "header"
      name: "x-rh-identity"
      type: "apiKey"
  schemas:
    DataPage:
      type: object
      required:
        - data
        - links
        - meta
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/Baseline"
        links:
          type: object
          required:
            - first
            - last
            - next
            - previous
          properties:
            first:
              type: string
              format: url
            last:
              type: string
              format: url
            next:
              type: string
              format: url
            previous:
              type: string
              format: url
        meta:
          type: object
          required:
            - count
          properties:
            count:
              type: integer
    Error:
      type: object
      additionalProperties: false
      required:
        - detail
        - status
        - title
        - type
      properties:
        detail:
          type: string
        status:
          type: integer
        title:
          type: string
        type:
          type: string
    Baseline:
      type: object
      required:
        - account
        - created
        - display_name
        - id
        - updated
      properties:
        account:
          type: string
        baseline_facts:
          type: array
          items:
            $ref: "#/components/schemas/BaselineFact"
        created:
          type: string
          format: date
        display_name:
          type: string
        fact_count:
          type: integer
        id:
          type: string
          format: uuid
        updated:
          type: string
          format: date
    BaselineIn:
      type: object
      additionalProperties: false
      required:
        - display_name
      properties:
        display_name:
          type: string
        inventory_uuid:
          type: string
        baseline_facts:
          type: array
          items:
            $ref: "#/components/schemas/BaselineFact"
    JsonPatch:
      description: a JSON patch
      type: object
    BaselineFact:
      type: object
      additionalProperties: false
      required:
        - name
      properties:
        name:
          type: string
        value:
          type: string
        values:
          type: array
          items:
            type: object
            required:
              - name
              - value
            properties:
              name:
                type: string
              value:
                type: string
  parameters:
    offsetParam:
      name: offset
      in: query
      required: false
      schema:
        type: integer
        minimum: 0
        default: 0
      description: item number offset
    limitParam:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 50
      description: A number of items to return
    BaselineIds:
      in: path
      name: baseline_ids
      required: true
      schema:
        type: array
        items:
          type: string
    BaselineId:
      in: path
      name: baseline_id
      required: true
      schema:
        type: string
